name: Playground tests

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - uses: php-actions/phpunit@v3
      env:
        XDEBUG_MODE: coverage
      with:
        php_extensions: xdebug
        coverage_clover: clover.xml
    - name: Generate test coverage badge
      uses: timkrase/phpunit-coverage-badge@v1.2.0
      with:
        coverage_badge_path: 'badge-coverage.svg'
        push_badge: true
        repo_token: ${{ secrets.GITHUB_TOKEN }}